---
- name: Install Email Specter on Ubuntu
  hosts: all
  become: yes
  vars:
    mongodb_pkg_install: true
  roles:
    - role: trfore.mongodb_install

  tasks:
    -
    - name: Enable and start MongoDB
      systemd:
        name: mongod
        enabled: yes
        state: started

    - name: Ensure MongoDB is running
      wait_for:
        host: localhost
        port: 27017
        delay: 10
        timeout: 30

    - name: Install Go
      ansible.builtin.shell: |
        wget https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
        rm -rf /usr/local/go && tar -C /usr/local -xzf go{{ go_version }}.linux-amd64.tar.gz
        echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
        rm -rf go{{ go_version }}.linux-amd64.tar.gz
      args:
        executable: /bin/bash

    - name: Install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ nodejs_version }}.x | sudo -E bash -
        apt-get install -y nodejs

    - name: Create email-specter user
      user:
        name: email-specter
        shell: /bin/bash
        home: /home/email-specter
        create_home: yes

    - name: Create .email_specter config directory
      file:
        path: /home/email-specter/.email_specter
        state: directory
        owner: email-specter
        group: email-specter
        mode: '0755'

    - name: Place .env file in .email_specter folder
      template:
        src: templates/backend.env.j2
        dest: /home/email-specter/.email_specter/.env
        owner: email-specter
        group: email-specter
        mode: '0600'

    - name: Copy bounce_categories
      copy:
        src: ../config/bounce_categories
        dest: /home/email-specter/.email_specter/config
        owner: email-specter
        group: email-specter
        mode: '0600'

    - name: Copy service_providers
      copy:
        src: ../config/service_providers
        dest: /home/email-specter/.email_specter/config
        owner: email-specter
        group: email-specter
        mode: '0600'

    - name: Build Email Specter backend
      shell: |
        /usr/local/go/bin/go get email-specter
        /usr/local/go/bin/go build -o /usr/local/bin/email-specter
        chmod +x /usr/local/bin/email-specter
      args:
        chdir: ../

    - name: Place systemd unit file for email-specter
      template:
        src: templates/email-specter.service.j2
        dest: /etc/systemd/system/email-specter.service
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reexec

    - name: Enable and start email-specter service
      systemd:
        name: email-specter
        enabled: yes
        state: started

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Place .env file in frontend directory
      template:
        src: templates/frontend.env.j2
        dest: ../frontend/.env

    - name: Copy frontend to email-specter user home
      copy:
        src: ../frontend
        dest: /home/email-specter/frontend
        owner: email-specter
        group: email-specter
        mode: '0600'

    - name: Build the Frontend
      shell: |
        npm install
        npm run build
      args:
        chdir: /home/email-specter/frontend

    - name: Run the Frontend with PM2
      shell: |
        pm2 start npm --name email-specter-frontend -- start -- --port {{ frontend_port }}
        pm2 save
        pm2 startup
      args:
        chdir: /home/email-specter/frontend

  handlers:
    - name: Restart MongoDB
      systemd:
        name: mongod
        state: restarted